/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_management.h"

bool_t
d_print_nofile_1_svc(struct Peticion_server peticion, int *result,  struct svc_req *rqstp)
{
	bool_t retval = 1;
	printf("%s %s %s\n",peticion.nombre_usuario, peticion.nombre_peticion, peticion.fecha_hora);
	return retval;
}

bool_t
d_print_file_1_svc(struct Peticion_server peticion, int *result,  struct svc_req *rqstp)
{
	bool_t retval = 1;
	printf("%s %s %s %s\n",peticion.nombre_usuario, peticion.nombre_peticion, peticion.nombre_fichero, peticion.fecha_hora);
	return retval;
}

int
nanodt_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
