/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_management.h"

bool_t
xdr_Peticion_server (XDR *xdrs, Peticion_server *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_opaque (xdrs, objp->nombre_peticion, MAX_VALUE1))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->nombre_usuario, MAX_VALUE1))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->nombre_fichero, MAX_VALUE1))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->fecha_hora, MAX_VALUE1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->op_retorno_rpc))
		 return FALSE;
	return TRUE;
}
